# Generated by Django 5.2.7 on 2025-11-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_productsupply_battery_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsupply',
            name='chase_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
