# Generated by Django 5.2.7 on 2025-11-16 10:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_productsupply_chase_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name'], 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='dealer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productsupply',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Product Supplies'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='adminuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productsupply',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productsupply',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dealer',
            index=models.Index(fields=['branch', '-created_at'], name='dealers_branch__86c15a_idx'),
        ),
        migrations.AddIndex(
            model_name='dealer',
            index=models.Index(fields=['mobile_number'], name='dealers_mobile__44ecb3_idx'),
        ),
        migrations.AddIndex(
            model_name='productsupply',
            index=models.Index(fields=['dealer', '-created_at'], name='product_sup_dealer__0bdcd8_idx'),
        ),
        migrations.AddIndex(
            model_name='productsupply',
            index=models.Index(fields=['serial_number'], name='product_sup_serial__ddb987_idx'),
        ),
        migrations.AddIndex(
            model_name='productsupply',
            index=models.Index(fields=['product_name'], name='product_sup_product_08b906_idx'),
        ),
        migrations.AlterModelTable(
            name='adminuser',
            table='admin_users',
        ),
        migrations.AlterModelTable(
            name='branch',
            table='branches',
        ),
        migrations.AlterModelTable(
            name='dealer',
            table='dealers',
        ),
        migrations.AlterModelTable(
            name='productsupply',
            table='product_supplies',
        ),
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
    ]
